// Code generated by mockery v2.45.1. DO NOT EDIT.

package rest

import (
	context "context"

	rest "github.com/churmd/to-do-lists/internal/adapters/inbound/rest"
	mock "github.com/stretchr/testify/mock"
)

// StrictServerInterface is an autogenerated mock type for the StrictServerInterface type
type StrictServerInterface struct {
	mock.Mock
}

type StrictServerInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *StrictServerInterface) EXPECT() *StrictServerInterface_Expecter {
	return &StrictServerInterface_Expecter{mock: &_m.Mock}
}

// GetApiV1UsersUserIdTodos provides a mock function with given fields: ctx, request
func (_m *StrictServerInterface) GetApiV1UsersUserIdTodos(ctx context.Context, request rest.GetApiV1UsersUserIdTodosRequestObject) (rest.GetApiV1UsersUserIdTodosResponseObject, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for GetApiV1UsersUserIdTodos")
	}

	var r0 rest.GetApiV1UsersUserIdTodosResponseObject
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, rest.GetApiV1UsersUserIdTodosRequestObject) (rest.GetApiV1UsersUserIdTodosResponseObject, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, rest.GetApiV1UsersUserIdTodosRequestObject) rest.GetApiV1UsersUserIdTodosResponseObject); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(rest.GetApiV1UsersUserIdTodosResponseObject)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, rest.GetApiV1UsersUserIdTodosRequestObject) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StrictServerInterface_GetApiV1UsersUserIdTodos_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetApiV1UsersUserIdTodos'
type StrictServerInterface_GetApiV1UsersUserIdTodos_Call struct {
	*mock.Call
}

// GetApiV1UsersUserIdTodos is a helper method to define mock.On call
//   - ctx context.Context
//   - request rest.GetApiV1UsersUserIdTodosRequestObject
func (_e *StrictServerInterface_Expecter) GetApiV1UsersUserIdTodos(ctx interface{}, request interface{}) *StrictServerInterface_GetApiV1UsersUserIdTodos_Call {
	return &StrictServerInterface_GetApiV1UsersUserIdTodos_Call{Call: _e.mock.On("GetApiV1UsersUserIdTodos", ctx, request)}
}

func (_c *StrictServerInterface_GetApiV1UsersUserIdTodos_Call) Run(run func(ctx context.Context, request rest.GetApiV1UsersUserIdTodosRequestObject)) *StrictServerInterface_GetApiV1UsersUserIdTodos_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(rest.GetApiV1UsersUserIdTodosRequestObject))
	})
	return _c
}

func (_c *StrictServerInterface_GetApiV1UsersUserIdTodos_Call) Return(_a0 rest.GetApiV1UsersUserIdTodosResponseObject, _a1 error) *StrictServerInterface_GetApiV1UsersUserIdTodos_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *StrictServerInterface_GetApiV1UsersUserIdTodos_Call) RunAndReturn(run func(context.Context, rest.GetApiV1UsersUserIdTodosRequestObject) (rest.GetApiV1UsersUserIdTodosResponseObject, error)) *StrictServerInterface_GetApiV1UsersUserIdTodos_Call {
	_c.Call.Return(run)
	return _c
}

// NewStrictServerInterface creates a new instance of StrictServerInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStrictServerInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *StrictServerInterface {
	mock := &StrictServerInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
